Repository glpi-project/android-inventory-library, pull requests merged in 2018-12, with the labels that each got.

#201 Add manual installation
  _posts/static/2017-12-26-installation.md
Labels: documentation

#207 Remove changelog
  CHANGELOG.md
Labels: ci

#210 Release 1.0.0
  package.json
Labels: build, ci
