Repository glpi-project/android-inventory-library, pull requests merged in 2018-09, with the labels that each got.

#136 Add GPG steps
  _posts/static/2017-10-09-contributing.md
Labels: ci, documentation

#138 Add information operating system
  inventory/src/main/java/org/flyve/inventory/Utils.java
  inventory/src/main/java/org/flyve/inventory/categories/OperatingSystem.java
Labels: feature

#145 Add information about CPUs and Unit Test
  inventory/src/androidTest/java/org/flyve/inventory/CpusTest.java
  inventory/src/main/assets/cpu_family.json
  inventory/src/main/assets/cpu_manufacturer.json
  inventory/src/main/java/org/flyve/inventory/Utils.java
  inventory/src/main/java/org/flyve/inventory/categories/Cpus.java
Labels: feature

#148 Add information about Bios and Unit Test
  inventory/src/androidTest/java/org/flyve/inventory/BiosTest.java
  inventory/src/main/java/org/flyve/inventory/categories/Bios.java
Labels: feature

#150 Update headers
  inventory/src/androidTest/java/org/flyve/inventory/BiosTest.java
  inventory/src/androidTest/java/org/flyve/inventory/BluetoothTest.java
  inventory/src/androidTest/java/org/flyve/inventory/CamerasTest.java
  inventory/src/androidTest/java/org/flyve/inventory/ControllersTest.java
  inventory/src/androidTest/java/org/flyve/inventory/CpusTest.java
  inventory/src/androidTest/java/org/flyve/inventory/CreateFileTest.java
  inventory/src/androidTest/java/org/flyve/inventory/DrivesTest.java
  inventory/src/androidTest/java/org/flyve/inventory/HardwareTest.java
  inventory/src/androidTest/java/org/flyve/inventory/InputsTest.java
  inventory/src/androidTest/java/org/flyve/inventory/InventoryTaskTest.java
  inventory/src/androidTest/java/org/flyve/inventory/MemoryTest.java
  inventory/src/androidTest/java/org/flyve/inventory/NetworksTest.java
  inventory/src/androidTest/java/org/flyve/inventory/SensorsTest.java
  inventory/src/androidTest/java/org/flyve/inventory/SimcardsTest.java
  inventory/src/androidTest/java/org/flyve/inventory/SoftwareTest.java
  inventory/src/androidTest/java/org/flyve/inventory/UsbTest.java
  inventory/src/androidTest/java/org/flyve/inventory/VideosTest.java
  inventory/src/main/java/org/flyve/inventory/FILog.java
  inventory/src/main/java/org/flyve/inventory/FlyveException.java
  inventory/src/main/java/org/flyve/inventory/InventoryTask.java
  inventory/src/main/java/org/flyve/inventory/Utils.java
  inventory/src/main/java/org/flyve/inventory/categories/Battery.java
  inventory/src/main/java/org/flyve/inventory/categories/Bios.java
  inventory/src/main/java/org/flyve/inventory/categories/Bluetooth.java
  inventory/src/main/java/org/flyve/inventory/categories/Cameras.java
  inventory/src/main/java/org/flyve/inventory/categories/Categories.java
  inventory/src/main/java/org/flyve/inventory/categories/Category.java
  inventory/src/main/java/org/flyve/inventory/categories/CategoryValue.java
  inventory/src/main/java/org/flyve/inventory/categories/Controllers.java
  inventory/src/main/java/org/flyve/inventory/categories/Cpus.java
  inventory/src/main/java/org/flyve/inventory/categories/Drives.java
  inventory/src/main/java/org/flyve/inventory/categories/Envs.java
  inventory/src/main/java/org/flyve/inventory/categories/Hardware.java
  inventory/src/main/java/org/flyve/inventory/categories/Inputs.java
  inventory/src/main/java/org/flyve/inventory/categories/Jvm.java
  inventory/src/main/java/org/flyve/inventory/categories/LocationProviders.java
  inventory/src/main/java/org/flyve/inventory/categories/Memory.java
  inventory/src/main/java/org/flyve/inventory/categories/Networks.java
  inventory/src/main/java/org/flyve/inventory/categories/OperatingSystem.java
  inventory/src/main/java/org/flyve/inventory/categories/PhoneStatus.java
  inventory/src/main/java/org/flyve/inventory/categories/Processes.java
  inventory/src/main/java/org/flyve/inventory/categories/Sensors.java
  inventory/src/main/java/org/flyve/inventory/categories/Simcards.java
  inventory/src/main/java/org/flyve/inventory/categories/Software.java
  inventory/src/main/java/org/flyve/inventory/categories/Storage.java
  inventory/src/main/java/org/flyve/inventory/categories/StringUtils.java
  inventory/src/main/java/org/flyve/inventory/categories/Usb.java
  inventory/src/main/java/org/flyve/inventory/categories/User.java
  inventory/src/main/java/org/flyve/inventory/categories/Videos.java
  inventory/src/main/java/org/flyve/inventory/usbManager/SysBusUsbDevice.java
  inventory/src/main/java/org/flyve/inventory/usbManager/SysBusUsbDeviceFactory.java
  inventory/src/main/java/org/flyve/inventory/usbManager/SysBusUsbManager.java
  inventory/src/main/java/org/flyve/inventory/usbManager/UsbProperty.java
  inventory/src/main/java/org/flyve/inventory/usbManager/Validation.java
Labels: documentation

#155 Add information about external removable SD card
  inventory/src/androidTest/java/org/flyve/inventory/DrivesTest.java
  inventory/src/main/java/org/flyve/inventory/categories/Drives.java
Labels: bug, test

#157 Fix Battery get information changes
  inventory/src/androidTest/java/org/flyve/inventory/BatteryTest.java
  inventory/src/main/java/org/flyve/inventory/categories/Battery.java
Labels: bug, test

#158 Fix Software add and update information
  inventory/src/androidTest/java/org/flyve/inventory/SoftwareTest.java
  inventory/src/main/java/org/flyve/inventory/categories/Software.java
Labels: bug, test

#160 Add information about camera
  inventory/src/androidTest/java/org/flyve/inventory/CamerasTest.java
  inventory/src/main/AndroidManifest.xml
  inventory/src/main/assets/camera_vendors.json
  inventory/src/main/java/org/flyve/inventory/Utils.java
  inventory/src/main/java/org/flyve/inventory/categories/Cameras.java
  inventory/src/main/java/org/flyve/inventory/categories/Category.java
Labels: feature, test

#166 Add information about drives
  inventory/src/androidTest/java/org/flyve/inventory/DrivesTest.java
  inventory/src/main/java/org/flyve/inventory/categories/Drives.java
Labels: feature, test

#165 Removed return null in method getCatInfo
  inventory/src/main/java/org/flyve/inventory/Utils.java
  inventory/src/main/java/org/flyve/inventory/categories/Bios.java
  inventory/src/main/java/org/flyve/inventory/categories/Memory.java
Labels: bug

#168 Update Yarn
  yarn.lock
Labels: bug

#171 Add information about CPUs
  inventory/src/androidTest/java/org/flyve/inventory/CpusTest.java
  inventory/src/main/java/org/flyve/inventory/categories/Cpus.java
Labels: feature, test

#174 Activate and desactivate debug information
  example_kotlin/src/main/java/org/flyve/example_kotlin/MainActivity.kt
  inventory/src/main/java/org/flyve/inventory/InventoryTask.java
Labels: feature
