Repository glpi-project/android-inventory-library, pull requests merged in 2018-10, with the labels that each got.

#179 Remove character special of the output
  inventory/src/main/java/org/flyve/inventory/categories/CategoryValue.java
Labels: bug

#180 Convert timestamp in format date
  inventory/src/main/java/org/flyve/inventory/Utils.java
  inventory/src/main/java/org/flyve/inventory/categories/Software.java
Labels: bug, hacktoberfest

#183 Add information to output XML and JSON
  example_kotlin/src/main/java/org/flyve/example_kotlin/MainActivity.kt
  inventory/src/main/java/org/flyve/inventory/Utils.java
Labels: feature

#184 Add informaiton about operating system
  example_kotlin/src/main/java/org/flyve/example_kotlin/MainActivity.kt
  inventory/src/androidTest/java/org/flyve/inventory/BiosTest.java
  inventory/src/main/java/org/flyve/inventory/categories/Bios.java
Labels: feature, test

#187 Create partial information of the categories
  example_kotlin/src/main/java/org/flyve/example_kotlin/MainActivity.kt
  inventory/src/main/java/org/flyve/inventory/InventoryTask.java
Labels: feature

#186 Add information about networks
  inventory/src/androidTest/java/org/flyve/inventory/NetworksTest.java
  inventory/src/main/java/org/flyve/inventory/categories/Networks.java
Labels: feature, test

#196 Update inventory list
  README.md
Labels: documentation
