Repository glpi-project/android-inventory-library, pull requests merged in 2019-07, with the labels that each got.

#222 Added support to get serial number in android < 7
  inventory/src/main/java/org/flyve/inventory/categories/Bios.java
Labels: bug

#221 New Android versions
  inventory/src/main/java/org/flyve/inventory/categories/OperatingSystem.java
Labels: feature

#223 Maintenance commands
  ci/scripts/ci_setup.sh
Labels: build, ci
